#!/usr/bin/env bash

set -euo pipefail

me=${0##*/}
printf -v usage 'Usage:\n\t%s <filename (must not have colons `:`)>...\n' "$me"

if (($# == 0))
then
    printf '%s' "$usage"
    exit 1
fi

declare -a filenames=("$@")

for filename in "${filenames[@]}"
do
    if [[ $filename =~ ':' || ! -f $filename ]]
    then
        printf '%s' "$usage"
        exit 2
    fi
done

container_manager='docker'

if command -v podman &>/dev/null
then
    container_manager='podman'
fi

for filename in "${filenames[@]}"
do
    "$container_manager" run \
        --entrypoint=bash \
        --pull=never \
        --rm \
        --volume="$PWD/$filename:/home/colorized-logs/input" \
            colorized-logs \
                -c '
                    cd
                    ansi2txt <input >output
                    cp output input
                '
done
