#!/usr/bin/env perl

# Perl Bad Tests

use strict;
use warnings;

use Cwd;

die "Usage:\n\tbb [string pattern]\n" if @ARGV > 1;

my ($username) = cwd =~ qr{^/home/(.*?/|.*)};
$username or die "Unsupported working directory!\n";
$username =~ s{/}{};

chdir "/home/$username";

exec qw(egrep -Hn --), shift, 'BAD_TESTS.txt' if @ARGV;

exec qw(vim -O WORKING_MOOSE_TESTS.txt BAD_TESTS.txt);
