#!/usr/bin/env perl

# Perl Good Tests

use strict;
use warnings;

use Cwd;

die "Usage:\n\tbgood [string pattern]\n" if !@ARGV || @ARGV > 1;

my ($username) = cwd =~ qr{^/home/(.*?/|.*)};
$username or die "Unsupported working directory!\n";
$username =~ s{/}{};

my $search = shift;

my $finder = <<'EOT';
find `echo t/[0-9]* t/[!0-9]* lib bin | sed 's/[^ ]*\*[^ ]*/ /g'` \
    -name '*.t'                                                   \
    -exec bash -c 'exit `grep -cFx {} BAD_TESTS.txt`' \;          \
    -print
EOT

chdir "/home/$username";
print "$_\n" foreach grep /$search/, split /\n/, `$finder`;
