#!/usr/bin/env bash

set -euo pipefail

myname="$(basename "$0")"

if [[ $# -ne 1 || ! -f $1 ]]
then
    printf 'Usage: %s <filename>\n' "$myname"
    exit 1
fi

crtfile="$1"

openssl crl2pkcs7 -nocrl -certfile "$crtfile" | \
    openssl pkcs7 -print_certs -text -noout
