#!/usr/bin/env python3
"""Decode QR code using the ZXing library."""

from sys import stderr, argv
from zxing import BarCodeReader


def main():
    """The entry point."""

    my_name = argv[0]

    if len(argv) != 2:
        print("Usage:\n\t%s <filename>" % (my_name), file=stderr)
        exit(1)

    filename = argv[1]

    decoded = BarCodeReader().decode(filename, try_harder=False)
    if decoded:
        print(decoded)


if __name__ == '__main__':
    main()
