#!/usr/bin/env bash

set -euo pipefail

username='username'
password='password'
findword='search-term'

mysql -u"$username" -p"$password" 2>/dev/null <<< 'show databases;' | \
grep -Ev '.*_schema$|^mysql$|^sys$' | \
tail -n +2 | \
while read -r dbase
do
    printf 'Matches in database: %s\n' "$dbase"
    mysql -u"$username" -p"$password" "$dbase" 2>/dev/null <<< 'show tables;' | \
    tail -n +2 | \
    while read -r table
    do
        printf 'Matches in table: %s\n' "$table"
        mysql -u"$username" -p"$password" "$dbase" 2>/dev/null <<< "select * from $table" | \
            grep "$findword"
        echo
    done
    echo
done
