#!/usr/bin/env bash

set -euo pipefail

me="$(basename "$0")"

if [[
    $# != 2
    ||
    ! ( $1 =~ ^[a-z]([-a-z0-9]{4,28}[a-z0-9])$ )
    ||
    ! ( $2 =~ ^([0-9]{1,3}\.){3}([0-9]{1,3})$ )
   ]]
then
    printf 'Usage: %s <gcp-project-name> <dotted-decimal-IPv4-address>\n' "$me" >&2
    exit 1
fi

gcp_project="$1"
gce_vm_ip="$2"

gce_vm_name_zone_ip_csv="$(gcloud \
    --project "$gcp_project" \
    compute instances list \
    --format 'csv(name,zone,networkInterfaces[0].networkIP)' | \
    grep ",${gce_vm_ip//./\\.}\$" \
)"

gce_vm_name="$(cut -d, -f1 <<< "$gce_vm_name_zone_ip_csv")"
gce_vm_zone="$(cut -d, -f2 <<< "$gce_vm_name_zone_ip_csv")"

gcloud --project "$gcp_project" compute instances reset --zone "$gce_vm_zone" "$gce_vm_name"
