#!/usr/bin/env bash

set -euo pipefail

me="$(basename "$0")"

if [[
      $# != 2
        ||
      ! ( $1 =~ ^[a-z]([-a-z0-9]{4,28}[a-z0-9])$ )
        ||
      ! ( $2 =~ ^([0-9]{1,3}\.){3}([0-9]{1,3})$ )
]]
then
    printf 'Usage: %s <gcp-project-name> <dotted-decimal-IPv4-address>\n' "$me" >&2
    exit 1
fi

gcp_project="$1"
gce_vm_ip="$2"

gce_vm_name_and_zone_json="$(steampipe query --output json "
    select
        name,
        zone_name
    from
        gcp_project_${gcp_project//-/_}.gcp_compute_instance
    where
        network_interfaces -> 0 ->> 'networkIP' = '$gce_vm_ip'
" | jq .[0])"

gce_vm_name="$(jq -r .name <<< "$gce_vm_name_and_zone_json")"
gce_vm_zone="$(jq -r .zone_name <<< "$gce_vm_name_and_zone_json")"

gcloud --project "$gcp_project" compute instances reset --zone "$gce_vm_zone" "$gce_vm_name"
