#!/usr/bin/env bash

RANDOM_BITS_COUNT=512

test "$#" != 0 && echo "Usage: $(basename "$0")" && exit 1

echo "Change-Id: I$(dd if=/dev/urandom \
                       bs="$(( ("$RANDOM_BITS_COUNT" / 8) +
                            ! !("$RANDOM_BITS_COUNT" % 8) ))" \
                       count=1 2>/dev/null \
                    | git hash-object --stdin)"
