#!/usr/bin/env bash

set -euo pipefail

RANDOM_BITS_COUNT=512

if (($# != 0))
then
    printf 'Usage: %s\n' "$(basename "$0")"
    exit 1
fi

printf 'Change-Id: I%s\n' "$( \
    dd \
        if=/dev/urandom \
        bs="$(( (RANDOM_BITS_COUNT / 8) + ! !(RANDOM_BITS_COUNT % 8) ))" \
        count=1 \
    2>/dev/null \
    | \
    git hash-object --stdin \
)"
