#!/usr/bin/env bash

set -euo pipefail
shopt -s extglob

me="$(basename "$0")"

git submodule foreach "$me"

mapfile -t remotes <<<"$(git remote show -n)"

for remote in "${remotes[@]}"
do
    if [[ -z $remote ]]
    then
        continue
    fi
    url=$(git remote get-url "$remote")

    if [[ $url =~ ^ssh:// ]]
    then
        url=${url/#ssh:\/\/?(git@)/https://}
    elif [[ $url =~ ^git@ ]]
    then
        url=${url//:/\/}
        url=${url/#git@/https://}
    fi

    git remote set-url "$remote" "$url"
done
