#!/usr/bin/env bash

set -euo pipefail

me=${0##*/}

args=("$@")
for i in "${!args[@]}"
do
    case "${args[$i]}" in
        -h) ;&
        --help)
            printf 'Usage: %s [-<git-push-params>...] [branch]...\n' "$me"
            exit
            ;;

        -*)
            pushparams=("${pushparams[@]}" "${args[$i]}")
            unset 'args[$i]'
            ;;
    esac
done

if [[ -z $(git rev-parse --show-toplevel || :) ]]
then
    printf '%s: present directory must be in a Git repository\n' "$me"
    exit 1
fi

if ((${#args[@]} == 0))
then
    curbranch="$(git symbolic-ref --short HEAD 2>/dev/null || :)"
    if [[ -z $curbranch ]]
    then
        printf '%s: no branch checked out, and none specified\n' "$me"
        exit 2
    fi
    args=("$curbranch")
fi

remotes=('sgh' 'sgl' 'sbb')
for branch in "${args[@]}"
do
    for remote in "${remotes[@]}"
    do
        git push "${pushparams[@]}" "$remote" "$branch" &
    done
done

wait # guard against premature prompt
