#!/usr/bin/env bash

set -euo pipefail

me=${0##*/}

git submodule update --init
git submodule foreach "$me"

dot_git="$(git rev-parse --git-dir)"

for dot_git_item in \
    COMMIT_EDITMSG \
    FETCH_HEAD \
    ORIG_HEAD \
    description \
    hooks/ \
    info/exclude \

do
    rm -rf "${dot_git:?}/$dot_git_item"
done

git clean -ffdx
git checkout -f

mapfile -t remotes < <(git remote)

for remote in "${remotes[@]}"
do
    git remote prune "$remote"
done

git reflog expire --all --expire=now
git \
    -c gc.pruneExpire=now \
    -c gc.reflogExpire=0 \
    -c gc.reflogExpireUnreachable=0 \
    -c gc.rerereresolved=0 \
    -c gc.rerereunresolved=0 \
    \
    gc \
        --aggressive \
        --prune=now \
;
