#!/usr/bin/env bash

set -euo pipefail

me="$(basename "$0")"

gitroot="$(git rev-parse --show-toplevel)"

for dot_git_item in \
    COMMIT_EDITMSG \
    FETCH_HEAD \
    ORIG_HEAD \
    description \
    hooks/ \
    info/exclude \

do
    rm -rf "$gitroot/.git/$dot_git_item"
done

git clean -ffdx
git submodule foreach "$me"
git checkout -f
git submodule update --init --recursive

mapfile -t remotes < <(git remote)

for remote in "${remotes[@]}"
do
    git remote prune "$remote"
done

git reflog expire --all --expire=now
git -c gc.reflogExpire=0 \
    -c gc.reflogExpireUnreachable=0 \
    -c gc.rerereresolved=0 \
    -c gc.rerereunresolved=0 \
    -c gc.pruneExpire=now \
    gc --prune=now --aggressive
