#!/usr/bin/env bash

me="$(basename "$0")"

args=("$@")
for i in "${!args[@]}"
do
    case "${args[$i]}" in
        -h) ;&
        --help)
            echo "Usage: $me [-<git-push-params>...] [branch]..."
            exit
            ;;

        -*)
            pushparams=("${pushparams[@]}" "${args[$i]}")
            unset 'args[$i]'
            ;;
    esac
done

test -z "$(git rev-parse --show-toplevel)" && \
    echo "$me: present directory must be in a Git repository" && exit 1

if test "${#args[@]}" -eq 0
then
    curbranch="$(git symbolic-ref --short HEAD 2>/dev/null)"
    test -z "$curbranch" \
        && echo "$me: no branch checked out, and none specified" && exit 2
    args=("$curbranch")
fi

remotes=('sgh' 'sgl' 'sbb')
for branch in "${args[@]}"
do
    for remote in "${remotes[@]}"
    do
        git push "${pushparams[@]}" "$remote" "$branch" &
    done
done

wait # guard against premature prompt
