#!/usr/bin/env bash

set -euo pipefail

myname="$(basename "$0")"

if (($# != 2 && $# != 3))
then
    printf 'Usage: %s <username> <repository> [aws-region]\n' "$myname"
    exit 1
fi

if [[ -z $(git rev-parse --show-toplevel || :) ]]
then
    printf '%s: present directory must be in a Git repository\n' "$myname"
    exit 2
fi

username="$1"
repository="$2"
aws_region="${3:-ap-south-1}"

declare -A map
map=(
    [az]="git-codecommit.$aws_region.amazonaws.com/v1/repos"
    [bb]="bitbucket.org/$username"
    [gh]="github.com/$username"
    [gl]="gitlab.com/$username"
    [nb]="notabug.org/$username"
);

for remote in "${!map[@]}"
do
    hostpath="${map[$remote]}/$repository.git"

    git remote remove "$remote" || :
    git remote add "$remote" "https://$username@$hostpath"

    git remote remove "s$remote" || :
    git remote add "s$remote" "ssh://$hostpath"
done
