#!/usr/bin/env bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Portions © 2020 Ankit Pati
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

set -euo pipefail

me="$(basename "$0")"
mydir="$(dirname "$0")/"

GRADLE_VERSION='6.5.1'

# Use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
# Do not quote $JAVA_OPTS & $GRADLE_OPTS, as that is part of the contract.
# shellcheck disable=SC2206
JVM_OPTS=('-Xmx512m' '-Xms512m' $JAVA_OPTS $GRADLE_OPTS)

CLASSPATH="$mydir/../lib/gradle-launcher-$GRADLE_VERSION.jar"

# Increase the maximum file descriptors
ulimit -n "$(ulimit -H -n)"

exec java "${JVM_OPTS[@]}" -D"org.gradle.appname=$me" -classpath "$CLASSPATH" \
          'org.gradle.launcher.GradleMain' "$@"
