#!/usr/bin/env bash

set -euo pipefail

myname="$(basename "$0")"

test "$#" -eq 0 && printf "Usage:\n\t%s <username>...\n" "$myname" && exit 1

error_users=''

for username in "$@"
do
    # shellcheck disable=SC2029
    ssh my-server groups "$username" 2>'/dev/null' || \
        error_users="$username, $error_users"
done

# shellcheck disable=SC2001
error_users="$(echo "$error_users" | sed 's/, $//')"

test "$error_users" && \
    echo "No public key found for $error_users." >&2 && exit 2
