#!/usr/bin/env bash

set -euo pipefail

# Update the following using information from
# https://build.opensuse.org/package/show/devel:kubic:libcontainers:unstable/podman
# Look in the right pane for the latest supported Ubuntu release.
kubic_latest_ubuntu='23.10'

architecture="$(dpkg --print-architecture)"

repo_name='devel:kubic:libcontainers:unstable'
repo_url="https://download.opensuse.org/repositories/$repo_name/xUbuntu_$kubic_latest_ubuntu/"
repo_path="/etc/apt/sources.list.d/$repo_name.list"

keyring_url="$repo_url/Release.key"
keyring_path="/etc/apt/keyrings/${repo_name//:/_}.gpg"

curl "$keyring_url" \
    --fail \
    --location \
    --proto =https \
    --show-error \
    --silent \
    --tlsv1.3 \
| gpg --dearmor --output "$keyring_path"

cat <<EOF >"$repo_path"
deb [arch=$architecture signed-by=$keyring_path] $repo_url /
EOF

apt update
apt upgrade -y \
    buildah \
    podman \
    skopeo \
;
