#!/usr/bin/env bash

set -euo pipefail

mydir="$(dirname "$0")/"
CLASSPATH="$mydir:$CLASSPATH"

main_class_name="$1"
shift

javac -Xlint:all "${main_class_name//.//}.java"
exec java "$main_class_name" "$@"
