#!/usr/bin/env bash

mydir="$(dirname "$0")/"
CLASSPATH="$(sanitize_path "$mydir:$CLASSPATH")"

main_class_name="$1"
shift

javac -Xlint:all "${main_class_name//.//}.java" && \
    exec java "$main_class_name" "$@"
