#!/usr/bin/env bash

set -euo pipefail

myname="$(basename "$0")"

if [[ $# -ne 1 || ! -d $1 ]]
then
    printf 'Usage: %s <directory>\n' "$myname"
    exit 1
fi

TARGET_DIRECTORY="$1"

find "$TARGET_DIRECTORY" -type f -exec chmod 0600 {} +
find "$TARGET_DIRECTORY" -type d -exec chmod 0700 {} +
find "$TARGET_DIRECTORY" ! \( -type d -o -type f \) -print -delete
