#!/usr/bin/env bash

set -euo pipefail

myname="$(basename "$0")"
usage="Usage: $myname <input.pdf>"

if (($# != 1))
then
    printf '%s\n' "$usage"
    exit 1
fi

numpages="$(gs -q -d'NODISPLAY' \
               -c "($1) (r) file runpdfbegin pdfpagecount = quit")"

if [[ -z "$numpages" ]]
then
    numpages=0
fi

printf 'Processing %s pages...\n' "$numpages"

for ((counter = 1; counter <= numpages; ++counter))
do
    newname="$(printf '%s\n' "$1" | sed 's/\.pdf//g')"
    newnamenum="$newname-$counter.pdf"
    yes | gs -d'BATCH' -s"OutputFile=$newnamenum" -d"FirstPage=$counter" \
             -d"LastPage=$counter" -s'DEVICE=pdfwrite' "$1" >& '/dev/null'
done
