#!/usr/bin/env bash

set -euo pipefail

me=${0##*/}

if [[ $# -ne 1 || ! -f $1 ]]
then
    printf 'Usage: %s <filename.pbtxt>\n' "$me"
    exit 1
fi

config="$1"

adb shell perfetto -c - --txt -o '/data/misc/perfetto-traces/trace' < "$config"
