#!/usr/bin/env perl

use strict;
use warnings;

use Pod::Confluence;

my $NAME = (split m|/|, $0)[-1];
@ARGV or die "Usage:\n\t$NAME <file-with-POD>...\n";

foreach my $filename (@ARGV) {
    my $parser = Pod::Confluence->new;

    $parser->output_fh (*STDOUT);
    $parser->parse_file ($filename);

    print "\n";
}
