#!/usr/bin/env perl

use strict;
use warnings;

die "Usage:\n\tpt <filename>... [--no-select]\n"
    if not @ARGV or (@ARGV < 2 and grep /^--no-select$/, @ARGV);

my $noselect = grep /^--no-select$/, @ARGV;
@ARGV = grep !/^--no-select$/, @ARGV;

$ENV{HARNESS_PERL_SWITCHES} = '-MDevel::Cover';

s{^(.*/)?(.*)\.pm$}{${\($1 // '')}t/$2.t} foreach @ARGV;

system qw(find . -type d -name cover_db -exec rm -rf {} +);
system qw(prove -v), @ARGV;

foreach (@ARGV) { s{^t/}{}; s{/t/}{/}; s{\.t$}{\.pm}; }
system 'cover', ( $noselect ? qw(-ignore_re .*\.t$)
            : ('-select_re', '^'.( join '|', map quotemeta, @ARGV ).'$') );
