#!/usr/bin/env bash

set -euo pipefail

myname="$(basename "$0")"

if (($# == 0))
then
    printf 'Usage:\n\t%s <username>...\n' "$myname"
    exit 1
fi

error_users=''

for username in "$@"
do
    # shellcheck disable=SC2029
    ssh my-server sss_ssh_authorizedkeys "$username" 2>'/dev/null' || \
        error_users="$username, $error_users"
done

# shellcheck disable=SC2001
error_users="$(printf '%s\n' "$error_users" | sed 's/, $//')"

if [[ -n $error_users ]]
then
    printf 'No public key found for %s.\n' "$error_users" >&2
    exit 2
fi
