#!/usr/bin/env bash

set -euo pipefail

me=${0##*/}

if [[ $# -ne 1 || ! -d $1 ]]
then
    printf 'Usage: %s <directory>\n' "$me"
    exit 1
fi

TARGET_DIRECTORY="$1"

find "$TARGET_DIRECTORY" -type d               -exec chmod 0755 {} +
find "$TARGET_DIRECTORY" -type f   -executable -exec chmod 0755 {} +
find "$TARGET_DIRECTORY" -type f ! -executable -exec chmod 0644 {} +
