#!/usr/bin/env bash

myname="$(basename "$0")"

test "$#" -ne 1 -o ! -d "$1" && echo "Usage: $myname <directory>" && exit 1

TARGET_DIRECTORY="$1"

find "$TARGET_DIRECTORY" -type d               -exec chmod 0755 {} +
find "$TARGET_DIRECTORY" -type f   -executable -exec chmod 0755 {} +
find "$TARGET_DIRECTORY" -type f ! -executable -exec chmod 0644 {} +
