#!/usr/bin/env bash

set -euo pipefail

pfctl -ef - <<'EOF'
rdr pass inet proto tcp from any to any port 80 -> 127.0.0.1 port 8080
rdr pass inet proto tcp from any to any port 443 -> 127.0.0.1 port 8443
EOF
