#!/usr/bin/env bash

ssh remote mkdir '$HOME/.cache/var.cache.apt.archives/'
scp -r '/var/ftp/public_ftp/Ubuntu 16.04/32 bit/var.cache.apt.archives' remote:'$HOME/.cache/'

ssh remote '$HOME/bin/apt-clean.sh'

rm -rf '/var/ftp/public_ftp/Ubuntu 16.04/32 bit/var.cache.apt.archives'

scp -r remote:'$HOME/.cache/var.cache.apt.archives' '/var/ftp/public_ftp/Ubuntu 16.04/32 bit/'
ssh remote rm -rf '$HOME/.cache/var.cache.apt.archives/'
