#!/usr/bin/env bash

# Run this script twice on a new system, as root. It reboots in the middle, and
# picks up where it left off when run again after the reboot.

test -z "$(which tmux 2>/dev/null)" && \
    dnf install -y tmux && \
    tmux new-session 'touch .hushlogin; dnf upgrade --refresh -y; systemctl reboot'

me="$(basename "$0")"
mydir="$(dirname "$0")/"

test -z "$TMUX" && exec tmux new-session "bash $mydir/$me"

firewall-cmd --permanent --remove-service=cockpit
firewall-cmd --reload

dnf install -y epel-release || dnf install -y 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm'
dnf config-manager --set-enabled powertools || subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
dnf install -y \
    'https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm' \
    'https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm' \
    rpmfusion-free-release-tainted \
    rpmfusion-nonfree-release-tainted \
;
dnf upgrade --refresh -y
dnf install -y \
    ack \
    aria2 \
    bash-completion \
    cargo \
    git \
    man-pages \
    mlocate \
    npm \
    p7zip \
    perl-App-cpanminus \
    readline-devel \
    tree \
    util-linux-user \
    vim-enhanced \
;
dnf groupinstall -y 'Development Tools'

git clone 'https://gitlab.com/ankitpati/dotfiles.git'
make -C dotfiles/ install
rm -rf dotfiles/

git clone 'https://gitlab.com/ankitpati/scripts.git'
make -C scripts/ install
rm -rf scripts/

git clone 'https://gitlab.com/ankitpati/etc.git'
cp etc/sudoers.d/wheel-sudo-no-passwd /etc/sudoers.d/wheel-sudo-no-passwd
rm -rf etc/

git clone 'https://github.com/vlad2/git-sh.git'
make -C git-sh/ install
rm -rf git-sh/

npm install -g diff-so-fancy
updatedb
