#!/usr/bin/env bash

# Run this script twice on a new system, as root. It reboots in the middle, and
# picks up where it left off when run again after the reboot.

test -z "$(which tmux 2>/dev/null)" && \
    apt install -y tmux && \
    tmux new-session 'touch .hushlogin; apt dist-upgrade -y; apt autoremove -y; apt clean; systemctl reboot'

me="$(basename "$0")"
mydir="$(dirname "$0")/"

test -z "$TMUX" && exec tmux new-session "bash $mydir/$me"

ufw allow in ssh
ufw --force enable

snap remove --purge firefox

apt purge -y \
    aisleriot \
    apport\* \
    avahi\* \
    deja-dup\* \
    firefox\* \
    gdebi\* \
    gnome-mahjongg \
    gnome-mines \
    gnome-sudoku \
    gnome-todo \
    gufw \
    magnus \
    onboard\* \
    orca \
    shotwell \
    thunderbird \
    transmission \
    webcamoid\* \
;

add-apt-repository ppa:apt-fast/stable

# TODO: Only on Ubuntu MATE
#apt purge -y \
#    ayatana-indicator-keyboard \
#    ayatana-indicator-session \
#;
#apt install -y \
#    ayatana-indicator-datetime \
#    breeze \
#    cheese \
#;
#snap remove \
#    ubuntu-mate-welcome \
#;

apt install -y \
    ack \
    adb \
    apt-fast \
    apt-file \
    aria2 \
    bash-completion \
    bleachbit \
    breeze-icon-theme \
    build-essential \
    curl \
    dconf-editor \
    default-jdk \
    dos2unix \
    fastboot \
    ffmpeg \
    git \
    gnome-shell-extension-gpaste \
    gnome-tweaks \
    kolourpaint \
    libreoffice-java-common \
    lm-sensors \
    lvm2 \
    moreutils \
    nmap \
    openssh-server \
    p7zip \
    plasma-nm \
    plocate \
    podman \
    pwgen \
    shellcheck \
    speedtest-cli \
    tree \
    ubuntu-restricted-extras \
    vim-gtk3 \
    vlc \
    wireshark-qt \
;

usermod -aG wireshark ankitpati

aria2c -c -x 16 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'
apt install -y ./google-chrome-stable_current_amd64.deb
rm google-chrome-stable_current_amd64.deb

apt autoremove -y
apt clean

git clone 'https://gitlab.com/ankitpati/dotfiles.git'
make -C dotfiles/ install
rm -rf dotfiles/

git clone 'https://gitlab.com/ankitpati/scripts.git'
make -C scripts/ install
rm -rf scripts/

git clone 'https://gitlab.com/ankitpati/git-sh.git'
make -C git-sh/ install
rm -rf git-sh/

rm \
    ~/.bash_logout \
    ~/.cshrc \
    ~/.tcshrc \
;

apt-file update
updatedb
