#!/usr/bin/env bash

set -uo pipefail

# Some formulae are forcefully versioned by Homebrew, so upgrading to the
# latest needs some work.
brew_forced_version_formulae=(
    postgresql
)

container_manager="$(command -v podman 2>/dev/null || :)"
container_manager="${container_manager:-docker}"

brew update --force
brew upgrade

for brew_forced_version_formula in "${brew_forced_version_formulae[@]}"
do
    mapfile -t < <( \
        brew formulae |
            grep -- "^$brew_forced_version_formula@" |
            sort --reverse --version-sort \
    )

    old_version_present=''
    for brew_forced_version_old_formula in "${MAPFILE[@]:1}"
    do
        if brew uninstall -- "$brew_forced_version_old_formula"
        then
            old_version_present=1
        fi
    done

    if ((old_version_present == 1))
    then
        brew install -- "${MAPFILE[0]}"
    fi
done

cpan-outdated --exclude-core -p |
    xargs --no-run-if-empty -- cpan --

steampipe plugin update --all

tldr --update

"$container_manager" image ls --format='{{.Repository}}:{{.Tag}}' |
    grep --invert-match -- '^localhost/' |
    sed -- 's/:<none>$//' |
    xargs --max-args=1 --no-run-if-empty -- "$container_manager" pull --

mapfile -t -d '' < <(find "$HOME/.arkade/bin" -type f -executable -printf '%f\0')
for arktool in "${MAPFILE[@]}"
do
    arkade get "$arktool"
done

kubectl krew upgrade

mapfile -t < <(code --list-extensions)
for codext in "${MAPFILE[@]}"
do
    code --install-extension="$codext" --force
done

terraform_current_version=''
terraform_previous_version=''

mapfile -t terraform_available_versions < <(tfenv list-remote)
for terraform_available_version in "${terraform_available_versions[@]}"
do
    if [[ $terraform_available_version =~ - ]]
    then
        continue
    fi

    if [[ -z $terraform_current_version ]]
    then
        terraform_current_version=$terraform_available_version
        continue
    fi

    terraform_previous_version=$terraform_available_version
    break
done

tfenv install "$terraform_current_version"
tfenv use latest
tfenv uninstall "$terraform_previous_version"

if [[ $OSTYPE == *linux* ]]
then
    gcloud components update
elif [[ $OSTYPE == *darwin* ]]
then
    softwareupdate -l

    # Upgrading GCloud CLI through Homebrew resets installed components, and
    # they need to be reinstalled afterwards.
    mapfile -t gcloud_installed_components < <( \
        gcloud components list --format='json(id, state.name)' 2>/dev/null |
            jq --raw-output '.[] | select(.state.name == "Installed") | .id' \
    )

    brew upgrade --cask --greedy
    sudo --reset-timestamp

    gcloud components install "${gcloud_installed_components[@]}"
fi

vim +PlugUpgrade +PlugUpdate
nvim +PlugUpgrade +PlugUpdate
