#!/usr/bin/env bash

set -uo pipefail

# Some formulae are forcefully versioned by Homebrew, so upgrading to the
# latest needs some work.
brew_forced_version_formulae=(
    postgresql
)

container_manager=${ command -v podman 2>/dev/null || :; }
container_manager=${container_manager:-docker}

CLOUDSDK_CORE_DISABLE_PROMPTS=1
export CLOUDSDK_CORE_DISABLE_PROMPTS

pre_upgrade_perl_version=${ perl -E 'say $^V'; }
readonly pre_upgrade_perl_version

brew update --force
brew upgrade
brew outdated --formula --quiet |
    xargs --max-args=1 --no-run-if-empty -- brew upgrade --

for brew_forced_version_formula in "${brew_forced_version_formulae[@]}"
do
    mapfile -t < <( \
        brew formulae |
            grep -- "^$brew_forced_version_formula@" |
            sort --reverse --version-sort \
    )

    old_version_present=''
    for brew_forced_version_old_formula in "${MAPFILE[@]:1}"
    do
        if brew uninstall -- "$brew_forced_version_old_formula"
        then
            old_version_present=1
        fi
    done

    if ((old_version_present == 1))
    then
        brew install -- "${MAPFILE[0]}"
    fi
done

post_upgrade_perl_version=${ perl -E 'say $^V'; }
readonly post_upgrade_perl_version

if [[ $pre_upgrade_perl_version != "$post_upgrade_perl_version" ]]
then
    perl-local-lib-post-upgrade
fi

cpan-outdated --exclude-core -p |
    xargs --no-run-if-empty -- cpan --

steampipe plugin update --all

tldr --update

"$container_manager" image list --format='{{.Repository}}:{{.Tag}}' |
    grep --extended-regexp --invert-match -- '^localhost/|:.*[0-9]' |
    sed -- 's/:<none>$//' |
    xargs --max-args=1 --no-run-if-empty -- "$container_manager" pull --

mapfile -t -d '' < <(find "$HOME/.arkade/bin" -type f -executable -printf '%f\0')
for arktool in "${MAPFILE[@]}"
do
    arkade get "$arktool"
done

kubectl krew upgrade

code --update-extensions

terraform_current_version=''
terraform_previous_version=''

mapfile -t terraform_available_versions < <(tfenv list-remote)
for terraform_available_version in "${terraform_available_versions[@]}"
do
    if [[ $terraform_available_version =~ - ]]
    then
        continue
    fi

    if [[ -z $terraform_current_version ]]
    then
        terraform_current_version=$terraform_available_version
        continue
    fi

    terraform_previous_version=$terraform_available_version
    break
done

tfenv install "$terraform_current_version"
tfenv use latest
tfenv uninstall "$terraform_previous_version"

if [[ $OSTYPE == *linux* ]]
then
    gcloud components update
elif [[ $OSTYPE == *darwin* ]]
then
    softwareupdate -l

    # Upgrading GCloud CLI through Homebrew resets installed components, and
    # they need to be reinstalled afterwards.
    mapfile -t gcloud_installed_components < <( \
        gcloud components list --format='json(id, state.name)' 2>/dev/null |
            jq --raw-output '.[] | select(.state.name == "Installed") | .id' \
    )

    brew upgrade --cask --greedy
    brew outdated --cask --greedy --quiet |
        xargs --max-args=1 --no-run-if-empty -- brew upgrade --cask --greedy --
    sudo --reset-timestamp

    gcloud components install "${gcloud_installed_components[@]}"
fi

vim +PlugUpgrade +PlugUpdate +quitall
nvim +PlugUpgrade +PlugUpdate
