#!/usr/bin/env bash

proc="$(docker ps -a -q)"
test -n "$proc" && echo "$proc" | xargs -r docker stop

docker container prune -f
docker image prune -f
docker network prune -f
docker volume prune -f
#docker image prune -af
