#!/usr/bin/env bash

set -euo pipefail

 docker ps --all --quiet | xargs --no-run-if-empty docker rm --force
 docker container prune       --force
 docker image     prune       --force
 docker network   prune       --force
 docker volume    prune --all --force
#docker image     prune --all --force
 docker buildx    prune --all --force --verbose
