#!/usr/bin/env bash

docker ps -a -q | xargs -r docker stop
docker container prune -f
docker image     prune -f
docker network   prune -f
docker volume    prune -f
docker builder   prune -f
#docker image     prune -fa
#docker builder   prune -fa
